---
- name: Install earlyoom
  apt:
    pkg:
      - earlyoom
    state:
      present
  retries: 5
  delay: 120

- name: Enable earlyoom
  systemd:
    name: earlyoom
    state: started
    enabled: yes
