---
- name: Prune Docker System
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Prune docker system for last 24 hours
      command: 'docker system prune -f --filter "until=24h"'
      async: 3600
      poll: 30
