---
- name: Rename Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - role: agent
    - role: statsd_exporter
    - role: filebeat
    - role: user_ssh_certificate
