---
- name: Install ufw
  package:
    name: ufw
    state: present

- name: Allow ssh port 22 from everywhere
  ufw:
    rule: allow
    to_port: ssh
    proto: tcp

- name: Allow https from everywhere
  ufw:
    rule: allow
    to_port: https
    proto: tcp

- name: Allow http from everywhere for proxy
  ufw:
    rule: allow
    to_port: http
    proto: tcp
  when: is_proxy_server|bool

- name: Allow http from proxy
  ufw:
    rule: allow
    from_ip: "{{ proxy_private_ip }}"
    to_port: http
    proto: tcp
  when: is_server|bool and proxy_private_ip is defined

- name: Allow mysql port 3306 connections
  ufw:
    rule: allow
    to_port: mysql
    proto: tcp
  when: is_database_server|bool

- name: Enable logging
  ufw:
    logging: "on"

- name: Deny incoming by default
  ufw:
    default: deny
    direction: incoming

- name: Allow outgoing by default
  ufw:
    default: allow
    direction: outgoing

- name: Enable ufw
  ufw:
    state: enabled

- name: Ensure ufw systemd service is enabled and running
  service:
    name: ufw
    enabled: yes
    state: started
