---
- name: Set JSON Variables
  set_fact:
    all_mounts: '{{ all_mounts_json | from_json }}'
    volume_mounts: '{{ volume_mounts_json | from_json }}'
    bind_mounts: '{{ bind_mounts_json | from_json }}'

- name: Mount Volumes
  mount:
    src: "{{ item.source }}"
    path: "{{ item.mount_point }}"
    fstype: "{{ item.filesystem }}"
    opts: "{{ item.mount_options }}"
    state: mounted
  loop: "{{ volume_mounts }}"

- name: Mount Bind Mounts
  mount:
    src: "{{ item.source }}"
    path: "{{ item.mount_point }}"
    fstype: none
    opts: "{{ item.mount_options }}"
    state: mounted
  loop: "{{ bind_mounts }}"

