---
- name: Get migrate script
  get_url:
    url: https://frappecloud.com/assets/press/migrate_2 
    dest: "/home/benches/{{ bench }}/migrate_2"

- name: Run migrate on site
  command: "/home/benches/{{ bench }}/env/bin/python migrate_2 -s {{ site }} -u {{ username }} -p {{ password }} -f {{ version }}"
  args:
    chdir: /home/benches/{{ bench }}
